#  MoreCrating
#  by Mr.FantiVideo
#  2018 - 2019

# == Languages ============================================= #
#                                                            #
#  List of available languages:                              #
#  English: "en"  |  Spanish: "es"                           #
#  French : "fr"  |  Italian: "it"                           #
#  German: "de"   |  Portugese: "pt"                         #
#                                                            #
# ========================================================== #

language: "en"

# == Messages ============================================== #
#                                                            #
#  Change according to the language.                         #
#                                                            #
# ========================================================== #

messages:
  default:
    prefix: "&eMoreCrafting &8- "
  en:
    gui-title-main: "&8Main Menu"
    gui-title-craft: "&8Crafting"
    gui-title-furnace: "&8Furnace"
    gui-name-id-1: "&8"
    gui-name-id-2: "&7Leave"
    name-craft1: "&7Smooth Quartz"
    name-craft2: "&7Smooth Red Sandstone"
    name-craft3: "&7Smooth Sandstone"
    name-craft4: "&7Smooth Stone"
    name-craft5: "&7Grass Block"
    name-craft6: "&7Grass Path"
    name-craft7: "&7Saddle"
    name-craft8: "&7Name Tag"
    name-craft9: "&7Ice &8(Crafting)"
    name-fire1: "&7Quartz Block"
    name-fire2: "&7Red Sandstone"
    name-fire3: "&7Sandstone"
    name-fire4: "&7Stone"
    name-fire5: "&7Brick"
    name-fire6: "&7Nether Brick"
    name-fire7: "&7End Stone"
    name-fire8: "&7Popped Chorus Fruit"
    name-fire9: "&7Prismarine Shard"
    name-fire10: "&7Quartz"
    name-fire11: "&7Magma Cream"
    name-fire12: "&7Packed Ice"
    name-fire13: "&7Ice &8(Furnace)"
    name-fire14: "&7Snowball"
    command-unknown: "&cUnknown command."
    command-reload: "&aReload complete."
    permission-denied: "&cYou do not have permission."
  fr:
    gui-title-main: "&8Menu Principal"
    gui-title-craft: "&8Fabrication"
    gui-title-furnace: "&8Fourneau"
    gui-name-id-1: "&8"
    gui-name-id-2: "&7Quitter"
    name-craft1: "&7Quartz lisse"
    name-craft2: "&7Grès rouge lisse"
    name-craft3: "&7Grès lisse"
    name-craft4: "&7Roche lisse"
    name-craft5: "&7Bloc d'herbe"
    name-craft6: "&7Chemin d'herbe"
    name-craft7: "&7Selle"
    name-craft8: "&7Étiquette"
    name-craft9: "&7Glace &8(Craft)"
    name-fire1: "&7Bloc de Quartz"
    name-fire2: "&7Grès rouge"
    name-fire3: "&7Grès"
    name-fire4: "&7Roche"
    name-fire5: "&7Brique"
    name-fire6: "&7Brique du Nether"
    name-fire7: "&7Pierre de L'End"
    name-fire8: "&7Chorus éclaté"
    name-fire9: "&7Éclat de prismarine"
    name-fire10: "&7Quartz"
    name-fire11: "&7Crème de magma"
    name-fire12: "&7Glace compactée"
    name-fire13: "&7Glace &8(Four)"
    name-fire14: "&7Boule de neige"
    command-unknown: "&cCommande Inconnue."
    command-reload: "&aReload terminé."
    permission-denied: "&cTu n'as pas la permission."
  de:
    gui-title-main: "&8Hauptmenü"
    gui-title-craft: "&8Herstellung"
    gui-title-furnace: "&8Ofen"
    gui-name-id-1: "&8"
    gui-name-id-2: "&7Verlassen"
    name-craft1: "&7Glatter Quarzblock"
    name-craft2: "&7Glatter roter Sandstein"
    name-craft3: "&7Glatter Sandstein"
    name-craft4: "&7Glatter Stein"
    name-craft5: "&7Grasblock"
    name-craft6: "&7Trampelpfad"
    name-craft7: "&7Sattel"
    name-craft8: "&7Namensschild"
    name-craft9: "&7Eis &8(Herstellung)"
    name-fire1: "&7Quartzblock"
    name-fire2: "&7Roter Sandstein"
    name-fire3: "&7Sandstein"
    name-fire4: "&7Stein"
    name-fire5: "&7Ziegel"
    name-fire6: "&7Netherziegel"
    name-fire7: "&7Endstein"
    name-fire8: "&7Geplatzte Chorusfrucht"
    name-fire9: "&7Prismarinscherbe"
    name-fire10: "&7Netherquarz"
    name-fire11: "&7Magmacreme"
    name-fire12: "&7Packeis"
    name-fire13: "&7Eis &8(Ofen)"
    name-fire14: "&7Schneeball"
    command-unknown: "&cUnbekannter Befehl."
    command-reload: "&aNachladen abgeschlossen."
    permission-denied: "&cDu hast keine Erlaubnis."
  es:
    gui-title-main: "&8Menú principal"
    gui-title-craft: "&8Elaboración"
    gui-title-furnace: "&8Horno"
    gui-name-id-1: "&8"
    gui-name-id-2: "&7Dejar"
    name-craft1: "&7Cuarzo liso"
    name-craft2: "&7Arenisca roja lisa"
    name-craft3: "&7Arenisca lisa"
    name-craft4: "&7Piedra lisa"
    name-craft5: "&7Césped"
    name-craft6: "&7Camino de césped"
    name-craft7: "&7Montura"
    name-craft8: "&7Etiqueta"
    name-craft9: "&7Hielo &8(Elaboración)"
    name-fire1: "&7Cuarzo"
    name-fire2: "&7Arenisca roja"
    name-fire3: "&7Arenisca"
    name-fire4: "&7Piedra"
    name-fire5: "&7Ladrillo"
    name-fire6: "&7Ladrillos del Nether"
    name-fire7: "&7Piedra del End"
    name-fire8: "&7Fruta coral horneada"
    name-fire9: "&7Fragmento de prismarina"
    name-fire10: "&7Cuarzo del Nether"
    name-fire11: "&7Crema de magma"
    name-fire12: "&7Hielo compacto"
    name-fire13: "&7Hielo &8(Horno)"
    name-fire14: "&7Bola de nieve"
    command-unknown: "&cComando desconocido."
    command-reload: "&aRecarga completa."
    permission-denied: "&cNo tienes permiso."
  it:
    gui-title-main: "&8Menu principale"
    gui-title-craft: "&8Crafting"
    gui-title-furnace: "&8Forno"
    gui-name-id-1: "&8"
    gui-name-id-2: "&7Lasciare"
    name-craft1: "&7Quarzo levigato"
    name-craft2: "&7Arenaria rossa levigata"
    name-craft3: "&7Arenaria levigata"
    name-craft4: "&7Pietra levigata"
    name-craft5: "&7Blocco d'erba"
    name-craft6: "&7Sentiero d'erba"
    name-craft7: "&7Sella"
    name-craft8: "&7Targhetta"
    name-craft9: "&7Ghiaccio &8(Crafting)"
    name-fire1: "&7Blocco di quarzo"
    name-fire2: "&7Arenaria rossa"
    name-fire3: "&7Arenaria"
    name-fire4: "&7Pietra"
    name-fire5: "&7Mattone"
    name-fire6: "&7Mattone del Nether"
    name-fire7: "&7Pietra dell'End"
    name-fire8: "&7Furtto di chorus scoppiato"
    name-fire9: "&7Scheggia di prismarino"
    name-fire10: "&7Quarzo del Nether"
    name-fire11: "&7Crema di magma"
    name-fire12: "&7Ghiaccio compatto"
    name-fire13: "&7Ghiaccio &8(Forno)"
    name-fire14: "&7Palla di neve"
    command-unknown: "&cComando sconosciuto."
    command-reload: "&aRicarica completata."
    permission-denied: "&cNon hai il permesso."
  pt:
    gui-title-main: "&8Menu principal"
    gui-title-craft: "&8Artesanato"
    gui-title-furnace: "&8Forno"
    gui-name-id-1: "&8"
    gui-name-id-2: "&7Deixar"
    name-craft1: "&7Quartzo Liso"
    name-craft2: "&7Arenito Vermelho Polido"
    name-craft3: "&7Arenito Polido"
    name-craft4: "&7Pedra Lisa"
    name-craft5: "&7Bloco de Relva"
    name-craft6: "&7Caminho de Relva"
    name-craft7: "&7Sela"
    name-craft8: "&7Etiqueta"
    name-craft9: "&7Gelo &8(Artesanato)"
    name-fire1: "&7Bloco de Quartzo"
    name-fire2: "&7Arenito Vermelho"
    name-fire3: "&7Arenito"
    name-fire4: "&7Pedra"
    name-fire5: "&7Tijolo"
    name-fire6: "&7Tijolo do Nether"
    name-fire7: "&7Pedra do End"
    name-fire8: "&7Fruta do Coro Rebentada"
    name-fire9: "&7Pedaço de Prismarinho"
    name-fire10: "&7Quartzo do Nether"
    name-fire11: "&7Creme de Magma"
    name-fire12: "&7Gelo Compactado"
    name-fire13: "&7Gelo &8(Forno)"
    name-fire14: "&7Bola de Neve"
    command-unknown: "&cComando desconhecido."
    command-reload: "&aRecarregando concluído."
    permission-denied: "&cVocê não tem permissão."

# == Blocs / Items ========================================= #
#                                                            #
#  List of ID Minecraft :                                    #
#  https://minecraft-ids.grahamedgecombe.com/                #
#                                                            #
# ========================================================== #

items:
  book:
    enabled: true
    name: "&eMoreCrafting"
    lore: "&7by Mr.FantiVideo"
    id: ENCHANTED_BOOK
    id-craft-1: POPPY
    id-craft-2: BOOK
  craft1:
    enabled: true
    id: SMOOTH_QUARTZ
    id-craft-1: QUARTZ_BLOCK
  craft2:
    enabled: true
    id: SMOOTH_RED_SANDSTONE
    id-craft-1: RED_SANDSTONE
  craft3:
    enabled: true
    id: SMOOTH_SANDSTONE
    id-craft-1: SANDSTONE
  craft4:
    enabled: true
    id: SMOOTH_STONE
    id-craft-1: STONE
  craft5:
    enabled: true
    id: GRASS_BLOCK
    id-craft-1: DIRT
    id-craft-2: GRASS
  craft6:
    enabled: true
    id: GRASS_PATH
    id-craft-1: DIRT
    id-craft-2: STICK
  craft7:
    enabled: true
    id: SADDLE
    id-craft-1: LEATHER
    id-craft-2: IRON_INGOT
    id-craft-3: LEAD
    id-craft-4: BOWL
  craft8:
    enabled: true
    id: NAME_TAG
    id-craft-1: LEATHER
    id-craft-2: IRON_INGOT
    id-craft-3: LEAD
    id-craft-4: MAP
  craft9:
    enabled: true
    id: ICE
    id-craft-1: SNOWBALL
    id-craft-2: WATER_BUCKET
  fire1:
    enabled: true
    id: QUARTZ_BLOCK
    id-furnace-1: SMOOTH_QUARTZ
  fire2:
    enabled: true
    id: RED_SANDSTONE
    id-furnace-1: SMOOTH_RED_SANDSTONE
  fire3:
    enabled: true
    id: SANDSTONE
    id-furnace-1: SMOOTH_SANDSTONE
  fire4:
    enabled: true
    id: STONE
    id-furnace-1: SMOOTH_STONE
  fire5:
    enabled: true
    id: BRICK
    id-furnace-1: BRICKS
  fire6:
    enabled: true
    id: NETHER_BRICK
    id-furnace-1: NETHER_BRICKS
  fire7:
    enabled: true
    id: END_STONE
    id-furnace-1: END_STONE_BRICKS
  fire8:
    enabled: true
    id: POPPED_CHORUS_FRUIT
    id-furnace-1: PURPUR_BLOCK
  fire9:
    enabled: true
    id: PRISMARINE_SHARD
    id-furnace-1: PRISMARINE
  fire10:
    enabled: true
    id: QUARTZ
    id-furnace-1: QUARTZ_BLOCK
  fire11:
    enabled: true
    id: MAGMA_CREAM
    id-furnace-1: MAGMA_BLOCK
  fire12:
    enabled: true
    id: PACKED_ICE
    id-furnace-1: BLUE_ICE
  fire13:
    enabled: true
    id: ICE
    id-furnace-1: PACKED_ICE
  fire14:
    enabled: true
    id: SNOWBALL
    id-furnace-1: SNOW_BLOCK
  setting:
    id-gui-1: GRAY_STAINED_GLASS_PANE
    id-gui-2: DARK_OAK_DOOR
    
permissions:
  morecrafting.admin.reload: morecrafting.admin.reload
  morecrafting.admin.*: morecrafting.admin.*
  morecrafting.book: morecrafting.book
  morecrafting.*: morecrafting.*
