name: MoreCrafting
version: 3.5
author: MrFantiVideo
main: fr.mrfantivideo.morecrafting.Main
api-version: 1.15

commands:
  morecrafting:
    description: Plugin version.
  morecrafting help:
    description: All available commands.
  morecrafting book:
    description: Give the recipe book.
  morecrafting recipes:
    description: Displays available recipes.
  morecrafting reload:
    description: Reload configuration files.