name: MoreCrafting
version: 3.0
author: MrFantiVideo
main: net.mrfantivideo.morecrafting.Main
api-version: 1.13

commands:
    morecrafting:
        description: Plugin version.
    morecrafting help:
        description: All available commands.
    morecrafting book:
        description: Give the recipe book.
    morecrafting reload:
        description: Reload configuration files.