#  MoreCrating
#  by Mr.FantiVideo
#  2018 - 2019

# == Languages ============================================= #
#                                                            #
#  List of available languages:                              #
#  English: "en_US"  |  Spanish: "es_ES"                     #
#  French : "fr_FR"  |  Italian: "it_IT"                     #
#  German: "de_DE"   |  Portugese: "pt_PT"                   #
#                                                            #
# ========================================================== #

language: "en_US"

# == Blocs / Items ========================================= #
#                                                            #
#  List of ID Minecraft :                                    #
#  https://minecraft-ids.grahamedgecombe.com/                #
#                                                            #
#  List of Enchantment :                                     #
#                                                            #
#                                                            #
# ========================================================== #

recipes:
  crafting:
    RECIPE-1:
      enabled: true
      craft:
        result:
          id: GRASS_BLOCK
          id-amount: 6
          id-book: 0
          enchantments:
            arrowDmg:
              enchant: ARROW_DAMAGE
              enchant-level: 1
        slots:
          1: WHEAT_SEEDS
          2: WHEAT_SEEDS
          3: WHEAT_SEEDS
          4: DIRT
          5: DIRT
          6: DIRT
          7: DIRT
          8: DIRT
          9: DIRT
    RECIPE-2:
      enabled: true
      craft:
        result:
          id: GRASS_PATH
          id-amount: 6
          id-book: 1
        slots:
          1: STICK
          2: STICK
          3: STICK
          4: DIRT
          5: DIRT
          6: DIRT
          7: DIRT
          8: DIRT
          9: DIRT
    RECIPE-3:
      enabled: true
      craft:
        result:
          id: SADDLE
          id-amount: 1
          id-book: 2
        slots:
          1: LEATHER
          2: LEATHER
          3: LEATHER
          4: LEATHER
          5: IRON_INGOT
          6: LEATHER
          7: LEAD
          8: BOWL
          9: LEAD
    RECIPE-4:
      enabled: true
      craft:
        result:
          id: NAME_TAG
          id-amount: 1
          id-book: 3
        slots:
          1: IRON_INGOT
          2: LEAD
          4: LEAD
          5: MAP
          6: LEATHER
          8: LEATHER
          9: MAP
    RECIPE-5:
      enabled: true
      craft:
        result:
          id: ICE
          id-amount: 1
          id-book: 4
        slots:
          1: SNOWBALL
          2: SNOWBALL
          3: SNOWBALL
          4: SNOWBALL
          5: WATER_BUCKET
          6: SNOWBALL
          7: SNOWBALL
          8: SNOWBALL
          9: SNOWBALL

#    EXEMPLE-CRAFTING:
#      enabled: true
#      fire:
#        result:
#          name: "&eEXEMPLE"
#          lore: "&7A NEW CRAFTING RECIPE !"
#          id: GRASS
#          id-amount: 9
#          id-book: 23
#        slot:
#          1: DIRT
#          2: DIRT
#          3: DIRT
#          4: DIRT
#          5: DIRT
#          6: DIRT
#          7: DIRT
#          8: DIRT
#          9: DIRT
          
  furnace:
    FIRE-RECIPE-1:
      enabled: true
      fire:
        result:
          id: QUARTZ_BLOCK
          id-amount: 1
          id-book: 9
          experience: 0.10
          cooking-time: 100
        slot:
          1: SMOOTH_QUARTZ
    FIRE-RECIPE-2:
      enabled: true
      fire:
        result:
          id: RED_SANDSTONE
          id-amount: 1
          id-book: 10
          experience: 0.10
          cooking-time: 100
        slot:
          1: SMOOTH_RED_SANDSTONE
    FIRE-RECIPE-3:
      enabled: true
      fire:
        result:
          id: SANDSTONE
          id-amount: 1
          id-book: 11
          experience: 0.10
          cooking-time: 100
        slot:
          1: SMOOTH_SANDSTONE
    FIRE-RECIPE-4:
      enabled: true
      fire:
        result:
          id: STONE
          id-amount: 1
          id-book: 12
          experience: 0.10
          cooking-time: 100
        slot:
          1: SMOOTH_STONE
    FIRE-RECIPE-5:
      enabled: true
      fire:
        result:
          id: BRICK
          id-amount: 4
          id-book: 13
          experience: 0.10
          cooking-time: 100
        slot:
          1: BRICKS
    FIRE-RECIPE-6:
      enabled: true
      fire:
        result:
          id: NETHER_BRICK
          id-amount: 4
          id-book: 14
          experience: 0.10
          cooking-time: 100
        slot:
          1: NETHER_BRICKS
    FIRE-RECIPE-7:
      enabled: true
      fire:
        result:
          id: END_STONE
          id-amount: 4
          id-book: 15
          experience: 0.10
          cooking-time: 100
        slot:
          1: END_STONE_BRICKS
    FIRE-RECIPE-8:
      enabled: true
      fire:
        result:
          id: POPPED_CHORUS_FRUIT
          id-amount: 1
          id-book: 16
          experience: 0.10
          cooking-time: 100
        slot:
          1: PURPUR_BLOCK
    FIRE-RECIPE-9:
      enabled: true
      fire:
        result:
          id: PRISMARINE_SHARD
          id-amount: 4
          id-book: 17
          experience: 0.10
          cooking-time: 100
        slot:
          1: PRISMARINE
    FIRE-RECIPE-10:
      enabled: true
      fire:
        result:
          id: QUARTZ
          id-amount: 4
          id-book: 18
          experience: 0.10
          cooking-time: 100
        slot:
          1: QUARTZ_BLOCK
    FIRE-RECIPE-11:
      enabled: true
      fire:
        result:
          id: MAGMA_CREAM
          id-amount: 4
          id-book: 19
          experience: 0.10
          cooking-time: 100
        slot:
          1: MAGMA_BLOCK
    FIRE-RECIPE-12:
      enabled: true
      fire:
        result:
          id: PACKED_ICE
          id-amount: 9
          id-book: 20
          experience: 0.10
          cooking-time: 100
        slot:
          1: BLUE_ICE
    FIRE-RECIPE-13:
      enabled: true
      fire:
        result:
          id: ICE
          id-amount: 9
          id-book: 21
          experience: 0.10
          cooking-time: 100
        slot:
          1: PACKED_ICE

#    EXEMPLE-FURNACE:
#      enabled: true
#      fire:
#        result:
#          name: "&eEXEMPLE"
#          lore: "&7A NEW FURNACE RECIPE !"
#          id: DIRT
#          id-amount: 1
#          id-book: 24
#        slot:
#          1: GRASS
          
  smoking:
    SMOKING-RECIPE-1:
      enabled: true
      smoking:
        result:
          id: DIAMOND_SWORD
          id-amount: 1
          id-book: 23
          experience: 0.10
          cooking-time: 75
        slot:
          1: SNOW
          
  blasting:
    BLASTING-RECIPE-1:
      enabled: true
      blasting:
        result:
          id: DIAMOND_PICKAXE
          id-amount: 1
          id-book: 24
          experience: 0.10
          cooking-time: 50
        slot:
          1: SNOW_BLOCK
          
  stonecutting:
    STONECUTTING-RECIPE-1:
      enabled: true
      stonecutting:
        result:
          id: DIAMOND_HOE
          id-amount: 1
          id-book: 25
        slot:
          1: SNOW_BLOCK
          
  campfire:
    CAMPFIRE-RECIPE-1:
      enabled: true
      campfire:
        result:
          id: PACKED_ICE
          id-amount: 9
          id-book: 20
          cooking-time: 50
        slot:
          1: BLUE_ICE
    CAMPFIRE-RECIPE-2:
      enabled: true
      campfire:
        result:
          id: ICE
          id-amount: 9
          id-book: 21
          cooking-time: 50
        slot:
          1: PACKED_ICE
    CAMPFIRE-RECIPE-3:
      enabled: true
      campfire:
        result:
          id: SNOWBALL
          id-amount: 4
          id-book: 22
          cooking-time: 50
        slot:
          1: SNOW_BLOCK
          
others:
  book:
    enabled: true
    give-book: true
    craft:
      result:
        name: "&6MoreCrafting"
        lore: "&7by Mr.FantiVideo"
        id: KNOWLEDGE_BOOK
        id-amount: 1
      slots:
          1: SLIME_BALL
          2: SLIME_BALL
          3: SLIME_BALL
          4: SLIME_BALL
          5: BOOK
          6: SLIME_BALL
          7: SLIME_BALL
          8: SLIME_BALL
          9: SLIME_BALL
    gui:
      menu:
        size: 27
    