#  MoreCrating
#  by Mr.FantiVideo
#  2018 - 2020

# == Languages ============================================= #
#                                                            #
#  List of available languages:                              #
#  English: "en_US"  |  Spanish: "es_ES"                     #
#  French : "fr_FR"  |  Italian: "it_IT"                     #
#  German: "de_DE"   |  Portugese: "pt_PT"                   #
#                                                            #
# ========================================================== #

language: "en_US"

# == Debug Mode ============================================ #
#                                                            #
#  Lets you know the loaded recipes.                         #
#                                                            #
# ========================================================== #

debug: false

# == Blocs / Items ================================================================ #
#                                                                                   #
#  List of ID Minecraft :                                                           #
#  https://minecraft-ids.grahamedgecombe.com/                                       #
#                                                                                   #
#  List of Enchantment :                                                            #
#  ARROW_DAMAGE, ARROW_FIRE, ARROW_INFINITE, ARROW_KNOCKBACK, BINDING_CURSE,        #
#  CHANNELING, DAMAGE_ALL, DAMAGE_ARTHROPODS, DAMAGE_UNDEAD, DEPTH_STRIDER,         #
#  DIG_SPEED, DURABILITY, FIRE_ASPECT, FROST_WALKER, IMPALING, KNOCKBACK,           #
#  LOOT_BONUS_BLOCKS, LOOT_BONUS_MOBS, LOYALTY, LUCK, LURE, MENDING, MULTISHOT,     #
#  OXYGEN, PIERCING, PROTECTION_ENVIRONMENTAL, PROTECTION_EXPLOSIONS,               #
#  PROTECTION_FALL, PROTECTION_FIRE, PROTECTION_PROJECTILE, QUICK_CHARGE, RIPTIDE,  #
#  SILK_TOUCH, SWEEPING_EDGE, THORNS, VANISHING_CURSE, WATER_WORKER.                #
#                                                                                   #
#  List of Potion Effect :                                                          #
#  ABSORPTION, BAD_OMEN, BLINDNESS, CONDUIT_POWER, CONFUSION, DAMAGE_RESISTANCE,    #
#  DOLPHINS_GRACE, FAST_DIGGING, FIRE_RESISTANCE, GLOWING, HARM, HEAL,              #
#  HEALTH_BOOST, HERO_OF_THE_VILLAGE, HUNGER, INCREASE_DAMAGE, INVISIBILITY, JUMP,  #
#  LEVITATION, LUCK, NIGHT_VISION, POISON, REGENERATION, SATURATION, SLOW,          #
#  SLOW_DIGGING, SLOW_FALLING, SPEED, UNLUCK, WATER_BREATHING, WEAKNESS, WITHER.    #
#                                                                                   #
# ================================================================================= #

recipes:
  RECIPE-1:
    enabled: true
    recipe-type: CRAFTING_TABLE
    craft:
      slots:
        1: WHEAT_SEEDS
        2: WHEAT_SEEDS
        3: WHEAT_SEEDS
        4: DIRT
        5: DIRT
        6: DIRT
        7: DIRT
        8: DIRT
        9: DIRT
      result:
        material: GRASS_BLOCK
        amount: 6
  RECIPE-2:
    enabled: true
    recipe-type: CRAFTING_TABLE
    craft:
      slots:
        1: STICK
        2: STICK
        3: STICK
        4: DIRT
        5: DIRT
        6: DIRT
        7: DIRT
        8: DIRT
        9: DIRT
      result:
        material: GRASS_PATH
        amount: 6
  RECIPE-3:
    enabled: true
    recipe-type: CRAFTING_TABLE
    craft:
      slots:
        1: LEATHER
        2: LEATHER
        3: LEATHER
        4: LEATHER
        5: IRON_INGOT
        6: LEATHER
        7: LEAD
        8: BOWL
        9: LEAD
      result:
        material: SADDLE
        amount: 1
  RECIPE-4:
    enabled: true
    recipe-type: CRAFTING_TABLE
    craft:
      slots:
        1: IRON_INGOT
        2: LEAD
        4: LEAD
        5: MAP
        6: LEATHER
        8: LEATHER
        9: MAP
      result:
        material: NAME_TAG
        amount: 1
  RECIPE-5:
    enabled: true
    recipe-type: CRAFTING_TABLE
    craft:
      slots:
        1: SNOWBALL
        2: SNOWBALL
        3: SNOWBALL
        4: SNOWBALL
        5: WATER_BUCKET
        6: SNOWBALL
        7: SNOWBALL
        8: SNOWBALL
        9: SNOWBALL
      result:
        material: ICE
        amount: 1
  FIRE-RECIPE-1:
    enabled: true
    recipe-type: FURNACE
    craft:
      slots:
        0: SMOOTH_QUARTZ
      result:
        material: QUARTZ_BLOCK
        amount: 1
        experience: 0.10
        cooking-time: 100
  FIRE-RECIPE-2:
    enabled: true
    recipe-type: FURNACE
    craft:
      slots:
        0: SMOOTH_RED_SANDSTONE
      result:
        material: RED_SANDSTONE
        amount: 1
        experience: 0.10
        cooking-time: 100
  FIRE-RECIPE-3:
    enabled: true
    recipe-type: FURNACE
    craft:
      slots:
        0: SMOOTH_SANDSTONE
      result:
        material: SANDSTONE
        amount: 1
        experience: 0.10
        cooking-time: 100
  FIRE-RECIPE-4:
    enabled: true
    recipe-type: FURNACE
    craft:
      slots:
        0: SMOOTH_STONE
      result:
        material: STONE
        amount: 1
        experience: 0.10
        cooking-time: 100
  SMOKING-RECIPE-1:
    enabled: true
    recipe-type: SMOKING
    craft:
      slots:
        0: GOLDEN_APPLE
      result:
        material: GOLD_NUGGET
        amount: 1
        experience: 0.10
        cooking-time: 75
  BLASTING-RECIPE-1:
    enabled: true
    recipe-type: BLASTING
    craft:
      slots:
        0: BRICKS
      result:
        material: BRICK
        amount: 4
        experience: 0.10
        cooking-time: 65
  BLASTING-RECIPE-2:
    enabled: true
    recipe-type: BLASTING
    craft:
      slots:
        0: NETHER_BRICKS
      result:
        material: NETHER_BRICK
        amount: 4
        experience: 0.10
        cooking-time: 65
  BLASTING-RECIPE-3:
    enabled: true
    recipe-type: BLASTING
    craft:
      slots:
        0: END_STONE_BRICKS
      result:
        material: END_STONE
        amount: 4
        experience: 0.10
        cooking-time: 65
  BLASTING-RECIPE-4:
    enabled: true
    recipe-type: BLASTING
    craft:
      slots:
        0: PURPUR_BLOCK
      result:
        material: POPPED_CHORUS_FRUIT
        amount: 1
        experience: 0.10
        cooking-time: 65
  BLASTING-RECIPE-5:
    enabled: true
    recipe-type: BLASTING
    craft:
      slots:
        0: PRISMARINE
      result:
        material: PRISMARINE_SHARD
        amount: 4
        experience: 0.10
        cooking-time: 65
  BLASTING-RECIPE-6:
    enabled: true
    recipe-type: BLASTING
    craft:
      slots:
        0: QUARTZ_BLOCK
      result:
        material: QUARTZ
        amount: 4
        experience: 0.10
        cooking-time: 65
  BLASTING-RECIPE-7:
    enabled: true
    recipe-type: BLASTING
    craft:
      slots:
        0: MAGMA_BLOCK
      result:
        material: MAGMA_CREAM
        amount: 4
        experience: 0.10
        cooking-time: 65
  STONECUTTING-RECIPE-1:
    enabled: true
    recipe-type: STONE_CUTTING
    craft:
      slots:
        0: OAK_LOG
      result:
        material: OAK_WOOD
        amount: 1
  STONECUTTING-RECIPE-2:
    enabled: true
    recipe-type: STONE_CUTTING
    craft:
      slots:
        0: SPRUCE_LOG
      result:
        material: SPRUCE_WOOD
        amount: 1
  STONECUTTING-RECIPE-3:
    enabled: true
    recipe-type: STONE_CUTTING
    craft:
      slots:
        0: BIRCH_LOG
      result:
        material: BIRCH_WOOD
        amount: 1
  STONECUTTING-RECIPE-4:
    enabled: true
    recipe-type: STONE_CUTTING
    craft:
      slots:
        0: JUNGLE_LOG
      result:
        material: JUNGLE_WOOD
        amount: 1
  STONECUTTING-RECIPE-5:
    enabled: true
    recipe-type: STONE_CUTTING
    craft:
      slots:
        0: ACACIA_LOG
      result:
        material: ACACIA_WOOD
        amount: 1
  STONECUTTING-RECIPE-6:
    enabled: true
    recipe-type: STONE_CUTTING
    craft:
      slots:
        0: DARK_OAK_LOG
      result:
        material: DARK_OAK_WOOD
        amount: 1
  CAMPFIRE-RECIPE-1:
  enabled: true
  recipe-type: CAMPFIRE
  craft:
    slots:
      0: BLUE_ICE
    result:
      material: PACKED_ICE
      amount: 9
      cooking-time: 60
  CAMPFIRE-RECIPE-2:
    enabled: true
    recipe-type: CAMPFIRE
    craft:
      slots:
        0: PACKED_ICE
      result:
        material: ICE
        amount: 9
        cooking-time: 60
  CAMPFIRE-RECIPE-3:
    enabled: true
    recipe-type: CAMPFIRE
    craft:
      slots:
        0: SNOW_BLOCK
      result:
        material: SNOWBALL
        amount: 4
        cooking-time: 60

          #    EXEMPLE-CRAFTING-1:
          #      enabled: true
          #      craft:
          #        result:
          #          name: "&eEXEMPLE"
          #          lore: "&7A NEW CRAFTING RECIPE !"
          #          id: GRASS
          #          id-amount: 9
          #          id-book: 1
          #          enchantments:
          #            ENCHANT-1:
          #              enchant: ARROW_DAMAGE
          #              enchant-level: 1
          #            ENCHANT-2:
          #              enchant: KNOCKBACK
          #              enchant-level: 1
          #        slot:
          #          1: DIRT
          #          2: DIRT
          #          3: DIRT
          #          4: DIRT
          #          5: DIRT
          #          6: DIRT
          #          7: DIRT
          #          8: DIRT
          #          9: DIRT

          #    EXEMPLE-CRAFT-2:
          #      enabled: true
          #      craft:
          #        result:
          #          name: "&eEXEMPLE"
          #          lore: "&7A NEW CRAFTING RECIPE !"
          #          id: PLAYER_HEAD
          #          id-amount: 1
          #          id-book: 2
          #          uuid: a9929927-c695-476a-b132-0d77e6a84b41
          #        slots:
          #          5: APPLE

          #    EXEMPLE-CRAFT-3:
          #      enabled: true
          #      craft:
          #        result:
          #          name: "&eEXEMPLE"
          #          lore: "&7A NEW CRAFTING RECIPE !"
          #          id: POTION
          #          id-amount: 1
          #          id-book: 3
          #          potions:
          #            EFFECT-1:
          #              effect: BLINDNESS
          #              duration: 1000
          #              level: 3
          #              ambient: true
          #              particles: false
          #              icon: true
          #        slots:
          #          5: HONEY_BOTTLE
          #
          #    EXEMPLE-FURNACE:
          #      enabled: true
          #      craft:
          #        result:
          #          name: "&eEXEMPLE"
          #          lore: "&7A NEW FURNACE RECIPE !"
          #          id: GRASS
          #          id-amount: 9
          #          id-book: 2
          #          experience: 0.10
          #          cooking-time: 75
          #          enchantments:
          #            ENCHANT-1:
          #              enchant: ARROW_DAMAGE
          #              enchant-level: 1
          #            ENCHANT-2:
          #              enchant: KNOCKBACK
          #              enchant-level: 1
          #        slot:
          #          1: DIRT
          #
          #    EXEMPLE-SMOKING:
          #      enabled: true
          #      craft:
          #        result:
          #          name: "&eEXEMPLE"
          #          lore: "&7A NEW SMOKING RECIPE !"
          #          id: GRASS
          #          id-amount: 9
          #          id-book: 3
          #          experience: 0.10
          #          cooking-time: 75
          #          enchantments:
          #            ENCHANT-1:
          #              enchant: ARROW_DAMAGE
          #              enchant-level: 1
          #            ENCHANT-2:
          #              enchant: KNOCKBACK
          #              enchant-level: 1
          #        slot:
          #          1: DIRT
          #
          #    EXEMPLE-BLASTING:
          #      enabled: true
          #      craft:
          #        result:
          #          name: "&eEXEMPLE"
          #          lore: "&7A NEW BLASTING RECIPE !"
          #          id: GRASS
          #          id-amount: 9
          #          id-book: 4
          #          experience: 0.10
          #          cooking-time: 75
          #          enchantments:
          #            ENCHANT-1:
          #              enchant: ARROW_DAMAGE
          #              enchant-level: 1
          #            ENCHANT-2:
          #              enchant: KNOCKBACK
          #              enchant-level: 1
          #        slot:
          #          1: DIRT
          #
          #    EXEMPLE-STONECUTTING:
          #      enabled: true
          #      craft:
          #        result:
          #          name: "&eEXEMPLE"
          #          lore: "&7A NEW STONECUTTING RECIPE !"
          #          id: GRASS
          #          id-amount: 9
          #          id-book: 5
          #          enchantments:
          #            ENCHANT-1:
          #              enchant: ARROW_DAMAGE
          #              enchant-level: 1
          #            ENCHANT-2:
          #              enchant: KNOCKBACK
          #              enchant-level: 1
          #        slot:
          #          1: DIRT

          #    EXEMPLE-CAMPFIRE:
          #      enabled: true
          #      craft:
          #        result:
          #          name: "&eEXEMPLE"
          #          lore: "&7A NEW CAMPFIRE RECIPE !"
          #          id: GRASS
          #          id-amount: 9
          #          id-book: 2
          #          cooking-time: 75
          #          enchantments:
          #            ENCHANT-1:
          #              enchant: ARROW_DAMAGE
          #              enchant-level: 1
          #            ENCHANT-2:
          #              enchant: KNOCKBACK
        #              enchant-level: 1
        #        slot:
        #          1: DIRT

others:
  book:
    enabled: true
    give-book: true
    craft:
      result:
        name: "&6MoreCrafting"
        lore: "&7by Mr.FantiVideo"
        id: KNOWLEDGE_BOOK
        id-amount: 1
      slots:
        1: SLIME_BALL
        2: SLIME_BALL
        3: SLIME_BALL
        4: SLIME_BALL
        5: BOOK
        6: SLIME_BALL
        7: SLIME_BALL
        8: SLIME_BALL
        9: SLIME_BALL
    gui:
      menu:
        size: 27