#  MoreCrating
#  by Mr.FantiVideo
#  2018 - 2019

# == Languages ============================================= #
#                                                            #
#  List of available languages:                              #
#  English: "en_US"  |  Spanish: "es_ES"                     #
#  French : "fr_FR"  |  Italian: "it_IT"                     #
#  German: "de_DE"   |  Portugese: "pt_PT"                   #
#                                                            #
# ========================================================== #

language: "en_US"

# == Blocs / Items ========================================= #
#                                                            #
#  List of ID Minecraft :                                    #
#  https://minecraft-ids.grahamedgecombe.com/                #
#                                                            #
# ========================================================== #

recipes:
  crafting:
    RECIPE-1:
      enabled: true
      craft:
        result:
          id: SMOOTH_QUARTZ
          id-amount: 9
          id-book: 0
        slots:
          1: QUARTZ_BLOCK
          2: QUARTZ_BLOCK
          3: QUARTZ_BLOCK
          4: QUARTZ_BLOCK
          5: QUARTZ_BLOCK
          6: QUARTZ_BLOCK
          7: QUARTZ_BLOCK
          8: QUARTZ_BLOCK
          9: QUARTZ_BLOCK
    RECIPE-2:
      enabled: true
      craft:
        result:
          id: SMOOTH_RED_SANDSTONE
          id-amount: 9
          id-book: 1
        slots:
          1: RED_SANDSTONE
          2: RED_SANDSTONE
          3: RED_SANDSTONE
          4: RED_SANDSTONE
          5: RED_SANDSTONE
          6: RED_SANDSTONE
          7: RED_SANDSTONE
          8: RED_SANDSTONE
          9: RED_SANDSTONE
    RECIPE-3:
      enabled: true
      craft:
        result:
          id: SMOOTH_SANDSTONE
          id-amount: 9
          id-book: 2
        slots:
          1: SANDSTONE
          2: SANDSTONE
          3: SANDSTONE
          4: SANDSTONE
          5: SANDSTONE
          6: SANDSTONE
          7: SANDSTONE
          8: SANDSTONE
          9: SANDSTONE
    RECIPE-4:
      enabled: true
      craft:
        result:
          id: SMOOTH_STONE
          id-amount: 9
          id-book: 3
        slots:
          1: STONE
          2: STONE
          3: STONE
          4: STONE
          5: STONE
          6: STONE
          7: STONE
          8: STONE
          9: STONE
    RECIPE-5:
      enabled: true
      craft:
        result:
          id: GRASS_BLOCK
          id-amount: 6
          id-book: 4
        slots:
          1: WHEAT_SEEDS
          2: WHEAT_SEEDS
          3: WHEAT_SEEDS
          4: DIRT
          5: DIRT
          6: DIRT
          7: DIRT
          8: DIRT
          9: DIRT
    RECIPE-6:
      enabled: true
      craft:
        result:
          id: GRASS_PATH
          id-amount: 6
          id-book: 5
        slots:
          1: STICK
          2: STICK
          3: STICK
          4: DIRT
          5: DIRT
          6: DIRT
          7: DIRT
          8: DIRT
          9: DIRT
    RECIPE-7:
      enabled: true
      craft:
        result:
          id: SADDLE
          id-amount: 1
          id-book: 6
        slots:
          1: LEATHER
          2: LEATHER
          3: LEATHER
          4: LEATHER
          5: IRON_INGOT
          6: LEATHER
          7: LEAD
          8: BOWL
          9: LEAD
    RECIPE-8:
      enabled: true
      craft:
        result:
          id: NAME_TAG
          id-amount: 1
          id-book: 7
        slots:
          1: IRON_INGOT
          2: LEAD
          4: LEAD
          5: MAP
          6: LEATHER
          8: LEATHER
          9: MAP
    RECIPE-9:
      enabled: true
      craft:
        result:
          id: ICE
          id-amount: 1
          id-book: 8
        slots:
          1: SNOWBALL
          2: SNOWBALL
          3: SNOWBALL
          4: SNOWBALL
          5: WATER_BUCKET
          6: SNOWBALL
          7: SNOWBALL
          8: SNOWBALL
          9: SNOWBALL
#    EXEMPLE-CRAFTING:
#      enabled: true
#      fire:
#        result:
#          name: "&eEXEMPLE"
#          lore: "&7A NEW CRAFTING RECIPE !"
#          id: GRASS
#          id-amount: 9
#          id-book: 23
#        slot:
#          1: DIRT
#          2: DIRT
#          3: DIRT
#          4: DIRT
#          5: DIRT
#          6: DIRT
#          7: DIRT
#          8: DIRT
#          9: DIRT
          
  furnace:
    RECIPE-1:
      enabled: true
      fire:
        result:
          id: QUARTZ_BLOCK
          id-amount: 1
          id-book: 9
        slot:
          1: SMOOTH_QUARTZ
    RECIPE-2:
      enabled: true
      fire:
        result:
          id: RED_SANDSTONE
          id-amount: 1
          id-book: 10
        slot:
          1: SMOOTH_RED_SANDSTONE
    RECIPE-3:
      enabled: true
      fire:
        result:
          id: SANDSTONE
          id-amount: 1
          id-book: 11
        slot:
          1: SMOOTH_SANDSTONE
    RECIPE-4:
      enabled: true
      fire:
        result:
          id: STONE
          id-amount: 1
          id-book: 12
        slot:
          1: SMOOTH_STONE
    RECIPE-5:
      enabled: true
      fire:
        result:
          id: BRICK
          id-amount: 4
          id-book: 13
        slot:
          1: BRICKS
    RECIPE-6:
      enabled: true
      fire:
        result:
          id: NETHER_BRICK
          id-amount: 4
          id-book: 14
        slot:
          1: NETHER_BRICKS
    RECIPE-7:
      enabled: true
      fire:
        result:
          id: END_STONE
          id-amount: 4
          id-book: 15
        slot:
          1: END_STONE_BRICKS
    RECIPE-8:
      enabled: true
      fire:
        result:
          id: POPPED_CHORUS_FRUIT
          id-amount: 1
          id-book: 16
        slot:
          1: PURPUR_BLOCK
    RECIPE-9:
      enabled: true
      fire:
        result:
          id: PRISMARINE_SHARD
          id-amount: 4
          id-book: 17
        slot:
          1: PRISMARINE
    RECIPE-10:
      enabled: true
      fire:
        result:
          id: QUARTZ
          id-amount: 4
          id-book: 18
        slot:
          1: QUARTZ_BLOCK
    RECIPE-11:
      enabled: true
      fire:
        result:
          id: MAGMA_CREAM
          id-amount: 4
          id-book: 19
        slot:
          1: MAGMA_BLOCK
    RECIPE-12:
      enabled: true
      fire:
        result:
          id: PACKED_ICE
          id-amount: 9
          id-book: 20
        slot:
          1: BLUE_ICE
    RECIPE-13:
      enabled: true
      fire:
        result:
          id: ICE
          id-amount: 9
          id-book: 21
        slot:
          1: PACKED_ICE
    RECIPE-14:
      enabled: true
      fire:
        result:
          id: SNOWBALL
          id-amount: 4
          id-book: 22
        slot:
          1: SNOW_BLOCK
#    EXEMPLE-FURNACE:
#      enabled: true
#      fire:
#        result:
#          name: "&eEXEMPLE"
#          lore: "&7A NEW FURNACE RECIPE !"
#          id: DIRT
#          id-amount: 1
#          id-book: 24
#        slot:
#          1: GRASS
          
others:
  book:
    enabled: true
    craft:
      result:
        name: "&eMoreCrafting"
        id: ENCHANTED_BOOK
        id-amount: 1
        lore: "&7by Mr.FantiVideo"
      slots:
          1: POPPY
          2: POPPY
          3: POPPY
          4: POPPY
          5: BOOK
          6: POPPY
          7: POPPY
          8: POPPY
          9: POPPY
    gui:
      menu:
        size: 27
      crafting:
        size: 27
      furnace:
        size: 9
  setting:
    id-gui-1: GRAY_STAINED_GLASS_PANE
    id-gui-2: DARK_OAK_DOOR
    